name: otp_field_premium
description: "This Package is ideal for developers who want to create secure and elegant OTP input experiences."
version: 0.0.6
repository: "https://github.com/jbjason/otp_field_premium/tree/main"

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - CHANGELOG.md
    - assets/

  fonts:
    - family: Rubik_Regular
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf

    - family: Rubik_Medium
      fonts:
        - asset: assets/fonts/rubik/Rubik-Medium.ttf

    - family: Rubik_Bold
      fonts:
        - asset: assets/fonts/rubik/Rubik-Bold.ttf

    - family: Rubik_Black
      fonts:
        - asset: assets/fonts/rubik/Rubik-Black.ttf

    - family: Poppins_Regular
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf

    - family: Poppins_Medium
      fonts:
        - asset: assets/fonts/poppins/Poppins-Medium.ttf

    - family: Poppins_Bold
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf

    - family: Poppins_Black
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
